status = ["build (10.x, ubuntu-latest)", "build (10.x, macos-latest)", "build (10.x, windows-latest)",
    "build (12.x, ubuntu-latest)", "build (12.x, macos-latest)", "build (12.x, windows-latest)"]
use_squash_merge = true
delete_merged_branches = true
